version: '3.3'
services:

  pod:
    container_name: 'pod'
    ports:
      - '9090:9090'
      - '3000:3000'
    image: 'alpine'
    tty: true

  prometheus:
    build: './prometheus'
    network_mode: 'service:pod'
    container_name: 'prometheus'
    depends_on:
      - 'pod'

  grafana:
    build: './grafana'
    network_mode: 'service:pod'
    container_name: 'grafana'
    depends_on:
      - 'pod'
