global:
  scrape_interval: '5s'
  evaluation_interval: '5s'

scrape_configs:

  - job_name: 'docker'
    static_configs:
      - targets:
        - 'localhost:2375'
        labels:
          instance: 'instance-1'
