global:
  scrape_interval: '5s'
  evaluation_interval: '5s'

scrape_configs:

  - job_name: 'docker'
    static_configs:
      - targets:
        - 'host.docker.internal:9100'
        labels:
          instance: 'instance-1'
